# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Number')),
                ('order_type', models.CharField(choices=[('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='delivery', max_length=20, verbose_name='Order type')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Customer name')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Customer phone')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Delivery address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered at')),
                ('promised_at', models.DateTimeField(blank=True, null=True, verbose_name='Promised at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery fee')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, max_length=30, verbose_name='Payment method')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'delivery_order',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum order')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery fee')),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='Minutes', verbose_name='Estimated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('zip_codes', models.JSONField(blank=True, default=list, verbose_name='ZIP codes')),
                ('max_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Max radius (km)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'db_table': 'delivery_zone',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('vehicle_type', models.CharField(blank=True, max_length=30, verbose_name='Vehicle type')),
                ('is_external', models.BooleanField(default=False, verbose_name='External driver')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'delivery_driver',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('product_name', models.CharField(max_length=200, verbose_name='Product name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliveryorder', verbose_name='Order')),
            ],
            options={
                'db_table': 'delivery_order_item',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('default_prep_time', models.PositiveIntegerField(default=20, help_text='Minutes', verbose_name='Default prep time')),
                ('auto_assign_zone', models.BooleanField(default=True, verbose_name='Auto assign zone')),
            ],
            options={
                'verbose_name': 'Delivery Settings',
                'verbose_name_plural': 'Delivery Settings',
                'db_table': 'delivery_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryzone', verbose_name='Delivery zone'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.driver', verbose_name='Driver'),
        ),
    ]
